routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});
*/

Auth::routes();

//security issues
Route::redirect('/register', '/');
Route::redirect('/password/reset', '/');
Route::redirect('/password/email', '/');
//End Security issues


Route::get('/', 'WebsiteController@index')->name('index');

Route::post('/subscribe','WebsiteController@subscribe')->name('subscribe');
Route::post('/check-email-validate','WebsiteController@isSetEmail')->name('subscribe');


Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/','AdminController@index')->name('admin');
    Route::get('/players','AdminController@players')->name('players');

    Route::get('/subscribers','AdminController@subscribers')->name('subscribers');

    Route::resource('players', 'PlayerController');

    Route::get('/players/emails/edit/{player_espn_id?}', 'PlayerController@showEditEmail')->name('players.email.edit');
    Route::post('/players/emails/edit/', 'PlayerController@editEmail');
    
    Route::get('/players/weekly-data/update', 'PlayerController@updatePlayerWeklyData');
    Route::get('/players/all/search', 'PlayerController@searchPlayer');

    Route::get('/players/id/search', 'PlayerController@showPlayer')->name('search-player');

    Route::resource('subscribers', 'SubscribersController');
});


Route::get('/admin/trend-players-mail', 'MailController@sendTrendPlayersMail')->name('trend-players-mail');
Route::get('/scrap-pga/', 'MailController@scrapPgaData');



Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    
    return "Cache is cleared";
});

app/Models/Subscriber.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    public $timestamps = false;
    /**
     * @var string
     */
    public $table = 'subscribers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'player_espn_id','email', 'status',
    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsToMany
    */
    public function playerData()
    {
        return $this->hasMany('App\Models\PlayerHasSubscriber', 'subscriber_id');
    }

    public function getPlayers()
    {
        $players  = $this->playerData->map(function($item, $index) {
            return $item->player;
        });

        return $players;
    }
}

app/Http/Controllers/SubscribersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreSubscriberRequest;
use Illuminate\Support\Facades\DB;
use Validator;
use App\Models\Subscriber;
use App\Models\Player;

class SubscribersController extends Controller
{
    protected $paginationCount = 10;

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subscribers = Subscriber::paginate($this->paginationCount);

        $data = [
            'subscribers' => $subscribers,
        ];

        return view('subscribers/index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $players = Player::all();

        $data = [
            'players' => $players,
        ];

        return view('subscribers/add')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSubscriberRequest $request)
    {
        $data = $request->all();

        $subscriber = Subscriber::create([
            'email' => $request->subscriber_email,
        ]);

        // if ($subscriber instanceof Subscriber) {
        if ($subscriber instanceof Subscriber) {
            $data = [];

            foreach ($request->player_espn_ids as $playerId) {
                $data[] = [
                    'subscriber_id' => $subscriber->id,
                    'player_espn_id' => $playerId,
                ];
            }

            DB::table('player_has_subscribers')->insert($data);
            
            return back()->with('success','Subscribtion created successfully!');
        } else {
            return back()->with('error','Some problemms occured on server side!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/subscribers/add.blade.php
@extends('layouts.admin')
@push('header-links')
  <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-select.min.css') }}">
@endpush
@section('content')
<!-- Start: Topbar -->
<header id="topbar">
  <div class="topbar-left">
    <ol class="breadcrumb">
      <li class="crumb-active">
        <a href="/">Dashboard</a>
      </li>
      <li class="crumb-icon">
        <a href="/">
          <span class="glyphicon glyphicon-home"></span>
        </a>
      </li>
      <li class="crumb-link">
        <a>{{ Route::currentRouteNamed('subscribers.create') ? 'Add' : 'Edit' }} Subscriber</a>
      </li>
      <!--<li class="crumb-trail">Dashboard</li>-->
    </ol>
  </div>

</header>
<!-- End: Topbar -->
<section id="content" class="table-layout animated fadeIn">
        <!-- begin: .tray-center -->
        <div class="tray tray-center">

          <div class="mw1000 center-block">

                    <div class="tray tray-center">

                    <!-- Validation Example -->
                    <div class="admin-form theme-primary mw1000 center-block" style="padding-bottom: 175px;">
                        <div class="panel">
                            <div class="panel-heading">
                              <span class="panel-title">Add Subscriber</span>
                            </div>
                            <div class="panel-body">
                                <form id="admin-form" class="form-horizontal" role="form" method="POST" action="{{ route('subscribers.store') }}" autocomplete="off">
                                <input type="hidden" name="id" value="{{ $edit_id ?? '' }}">
                                <input type="hidden" name="_method" value="{{ Route::currentRouteNamed('subscribers.create') ? 'POST' : 'PUT' }}">
                                {{ csrf_field() }}


                                <div class="form-group">
                                  <label for="email" class="col-lg-3 control-label">Email</label>

                                  <div class="col-lg-8">
                                    <label for="email" class="field {{ $errors->has('email') ? 'state-error' : ''}}">
                                        <input type="text" value="{{ !is_null(old('email')) ? old('email') : (isset($data) ? $data->email : '') }}" name="subscriber_email" id="email" class="gui-input" placeholder="Email">
                                    </label>
                                      @if($errors->has('subscriber_email'))
                                        <em for="email" class="state-error text-danger">{{ $errors->first('subscriber_email') }}</em>
                                      @endif
                                  </div>
                                </div>
                                <div class="form-group">
                                  <label for="fuel_type_id" class="col-lg-3 control-label">Choose Player</label>

                                  <div class="col-lg-8">
                                    <label for="player_espn_id" class="field {{ $errors->has('player_espn_id') ? 'state-error' : ''}}">
                                        <select  class="selectpicker w-100" name="player_espn_ids[]" data-live-search="true" multiple>
                                          @foreach($players as $key => $player)
                                              <option value="{{ $player->espn_id }}" {{ (!is_null(old('player_espn_id')) && isset($data) && $key == old('player_espn_id')) ? 'selected' : ((isset($data) && $player->player_espn_id == $key ) ? 'selected'  : '') }} >{{ $player->first_name.' '.$player->last_name }}</option>
                                           @endforeach
                                        </select>
                                    </label>

                                      @if($errors->has('player_espn_ids'))
                                        <em for="fuel_type_id" class="state-error text-danger">{{ $errors->first('player_espn_ids') }}</em>
                                      @endif
                                  </div>
                                </div>
                                <div class=" text-right">
                                    <button type="submit" class="button btn-primary">Add Subscriber</button>
                                    <a href="{{ url ('/admin/subscribers') }}" type="reset" class="button"> Cancel </a>
                                </div>
                              </form>
                            </div>
                        </div>
                    </div>
                    <!-- end: .admin-form -->
                </div>
                <!-- Begin: Admin Form -->
            </div>
        </div>
        <!-- end: .tray-center -->
</section>
@push('footer-scripts')
  <script src="{{ asset('js/bootstrap-select.min.js') }}"></script>
@endpush
@endsection

resources/views/subscribers/index.blade.php
@extends('layouts.admin')

@section('content')
<header id="topbar">
  <div class="topbar-left">
    <ol class="breadcrumb">
      <li class="crumb-active">
        <a href="">Dashboard</a>
      </li>
      <li class="crumb-icon">
        <a href="/">
          <span class="glyphicon glyphicon-home"></span>
        </a>
      </li>
      <li class="crumb-link">
        <a>Subscriber</a>
      </li>
      <!--<li class="crumb-trail">Dashboard</li>-->
    </ol>
  </div>

</header>

<section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
    <div class="tray tray-center">

        <div class="panel mb25 mt5">
            <div class="panel-body p25 pb5">
              <div class="tab-content pn br-n admin-form">
                  <div class="section row mbn">
                    <div class="col-sm-8">
                      <label class="field option mt10">
                        <!--<input type="checkbox" name="info" checked>-->
                        <span class=""></span>Add Subscriber
                      </label>
                    </div>
                    <div class="col-sm-4">
                      <p class="text-right">
                          <a href="{{ url('/admin/subscribers/create') }}" class="btn btn-primary" type="button">Add Subscriber</a>
                      </p>
                    </div>
                  </div>
                  <!-- end section -->
              </div>
            </div>
          </div>

          <div class="panel">
              <div class="panel-body pn">
                <div class="table-responsive">
                  <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                    <thead>
                      <tr class="bg-light">
                        <th class="text-center">#</th>
                        <th class="">Subscriber Email</th>
                        <th class="">Subscribed to Player</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach($subscribers as $subscriber)
                      <tr>
                          <td>{{ $subscriber->id }}</td>
                          <td>{{ $subscriber->email }}</td>
                          <td>
                            @if($subscriber->getPlayers()->isNotEmpty())
                              @foreach($subscriber->getPlayers() as $player)
                                <div><strong>({{ $loop->iteration }})&nbsp;&nbsp;&nbsp;</strong>{!! $player->fullName() !!}</div>
                              @endforeach
                            @endif
                          </td>
                      </tr>
                      @endforeach
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div class="panel-footer clearfix">
                  {{ $subscribers->links() }}
                  <a href="#" class="btn btn-success" style="float: right" role="button">Send Emails</a>
              </div>
          </div>
    </div>
</section>

@endsection

@section('page-js-script')
<script type="text/javascript">

</script>
@stop