routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});
*/

Auth::routes();

//security issues
Route::redirect('/register', '/');
Route::redirect('/password/reset', '/');
Route::redirect('/password/email', '/');
//End Security issues


Route::get('/', 'WebsiteController@index')->name('index');

Route::post('/subscribe','WebsiteController@subscribe')->name('subscribe');
Route::post('/check-email-validate','WebsiteController@isSetEmail')->name('subscribe');


Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/','AdminController@index')->name('admin');
    Route::get('/players','AdminController@players')->name('players');

    Route::get('/subscribers','AdminController@subscribers')->name('subscribers');

    Route::resource('players', 'PlayerController');

    Route::get('/players/emails/edit/{player_espn_id?}', 'PlayerController@showEditEmail')->name('players.email.edit');
    Route::post('/players/emails/edit/', 'PlayerController@editEmail');
    
    Route::get('/players/weekly-data/update', 'PlayerController@updatePlayerWeklyData');
    Route::get('/players/all/search', 'PlayerController@searchPlayer');

    Route::get('/players/id/search', 'PlayerController@showPlayer')->name('search-player');

    Route::resource('subscribers', 'SubscribersController');
});


Route::get('/admin/trend-players-mail', 'MailController@sendTrendPlayersMail')->name('trend-players-mail');
Route::get('/scrap-pga/', 'MailController@scrapPgaData');



Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    
    return "Cache is cleared";
});

app/Models/Player.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use ZingChart\PHPWrapper\ZC;

class Player extends Model
{
    public $timestamps = false;
    /**
     * @var string
     */
    public $table = 'players';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name',
    ];


    public static function fedexCupPlayers()
    {
        $players = Player::all();

        $data = collect([]);

        foreach ($players as $player) {
            if($player->isPlayInFedexCup()) {
                $data->push($player);
            }
        }

        return $data;
    }

    public function fedexData()
    {
        return $this->hasOne('App\Models\FedexCupPlayers', 'player_espn_id', 'espn_id');      
    }

    public function fedexResulst()
    {
        return $this->hasMany('App\Models\FedexCupResults', 'player_espn_id', 'espn_id');      
    }

    public function isPlayInFedexCup()
    {

        if($this->fedexData === null) {
            return false;
        } else {
            return true;
        }
    }

    public function generateEspnPlayerUrl()
    {
        $espnURL = 'http://www.espn.com/golf/player/results/_/id/' . $this->espn_id;

        return $espnURL;
    }

    public function tournaments()
    {
        return $this->hasMany('App\Models\PlayerTournamentData', 'player_espn_id', 'espn_id');
    }


    public function earnings()
    {
        return $this->hasMany('App\Models\PlayerTotalEarning', 'player_espn_id', 'espn_id')->orderBy('created_at', 'desc');
    }

    public function fullName()
    {
        return $this->first_name . '&nbsp;&nbsp;&nbsp;' . $this->last_name;
    }


    public function totalEarning()
    {   
        $earning = number_format((int)$this->earnings()->first()->earnings_in_one_year);
    
        $earning = '$' . $earning;


        return $earning;
    }
}

app/Http/Controllers/PlayerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Facades\DB;
use App\Models\FedexCupPlayers;
use App\Models\Player;
use Carbon\Carbon;

class PlayerController extends Controller
{
    protected $paginationCount = 10;

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $players = Player::paginate($this->paginationCount);

        $data = [
            'players' => $players,
            'paginationCount' => $this->paginationCount,
            'page' => $request->page ?? 0,
        ];


        return view('players/index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('players/add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = array(
           'first_name' => 'required|max:191',
           'last_name' => 'required|max:191',
        );

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
           return redirect('/players/create')
               ->withErrors($validator)->withInput();
        }

        $data = $request->all();
        
        Player::create($data);
        return redirect('/admin/players')->with('success','Player created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function showEditEmail($playerId)
    {   
        $player = Player::where('espn_id', $playerId)->get()->first();
        
        $data = [
            'player' => $player,
        ];

        return view('players.edit-email')->with($data);
    }

    public function editEmail(Request $request)
    {
        try {
            $result = Player::where('espn_id', $request->player_espn_id)->update(
                [
                    'email_text' => $request->email_text
            ]);

            return back()->with('success', 'Email text edited successfully!');
        } catch(\Throwable  $e) {
            return back()->with('error', 'Email text edit failed!');
        }
    }


    public function updatePlayerWeklyData()
    {
        \Artisan::call('players-data:update');
    }

    public function searchPlayer(Request $request)
    {
        $q = $request->q;

        $players = Player::where('first_name', 'like', "%$q%")
                        ->orWhere('last_name', 'like', "%$q%")
                        ->take(6)->get();

        $data = [];

        if ($players->isNotEmpty()) {
            foreach ($players as $player) {
                $data[] = [
                    'espn_id' => $player->espn_id,
                    'full_name' => $player->first_name . ' ' . $player->last_name,
                ];
            }
        }

        return response()->json($data);
    }

    public function showPlayer(Request $request)
    {
        $players = Player::paginate($this->paginationCount);
        $players = Player::where('espn_id', $request->espn_id)->paginate($this->paginationCount);

        $data = [
            'players' => $players,
            'paginationCount' => $this->paginationCount,
            'page' => $request->page ?? 0,
        ];


        return view('players/index')->with($data);        
    }
}

resources/views/players/add.blade.php
@extends('layouts.admin')

@section('content')
<!-- Start: Topbar -->
<header id="topbar">
  <div class="topbar-left">
    <ol class="breadcrumb">
      <li class="crumb-active">
        <a href="/">Dashboard</a>
      </li>
      <li class="crumb-icon">
        <a href="/">
          <span class="glyphicon glyphicon-home"></span>
        </a>
      </li>
      <li class="crumb-link">
        <a>{{ Route::currentRouteNamed('players.create') ? 'Add' : 'Edit' }} Project</a>
      </li>
      <!--<li class="crumb-trail">Dashboard</li>-->
    </ol>
  </div>

</header>
<!-- End: Topbar -->
<section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
        <div class="tray tray-center">

          <div class="mw1000 center-block">

                    <div class="tray tray-center">

                    <!-- Validation Example -->
                    <div class="admin-form theme-primary mw1000 center-block" style="padding-bottom: 175px;">
                        <div class="panel">
                            <div class="panel-heading">
                              <span class="panel-title">Add Player</span>
                            </div>
                            <div class="panel-body">
                                <form id="admin-form" class="form-horizontal" role="form" method="POST" action="{{ Route::currentRouteNamed('players.create') ? route('players.store') : route('players.update', ['id' => $data->id]) }}" autocomplete="off">
                                <input type="hidden" name="id" value="{{ $edit_id ?? '' }}">
                                <input type="hidden" name="_method" value="{{ Route::currentRouteNamed('players.create') ? 'POST' : 'PUT' }}">
                                {{ csrf_field() }}


                                <div class="form-group">
                                  <label for="name" class="col-lg-3 control-label">First Name</label>
                                  <div class="col-lg-8">
                                    <label for="name" class="field {{ $errors->has('first_name') ? 'state-error' : ''}}">
                                        <input type="text" value="{{ !is_null(old('first_name')) ? old('first_name') : (isset($data) ? $data->first_name : '') }}" name="first_name"  class="gui-input" placeholder="First Name">
                                    </label>
                                      @if($errors->has('first_name'))
                                      <em for="name" class="state-error">Enter first name</em>
                                      @endif
                                  </div>
                                </div>

                                <div class="form-group">
                                  <label for="name" class="col-lg-3 control-label">Last Name</label>
                                  <div class="col-lg-8">
                                    <label for="name" class="field {{ $errors->has('last_name') ? 'state-error' : ''}}">
                                        <input type="text" value="{{ !is_null(old('last_name')) ? old('last_name') : (isset($data) ? $data->last_name : '') }}" name="last_name" class="gui-input" placeholder="Last Name">
                                    </label>
                                      @if($errors->has('last_name'))
                                      <em for="last_name" class="state-error">Enter last name</em>
                                      @endif
                                  </div>
                                </div>

                                <div class=" text-right">
                                    <button type="submit" class="button btn-primary"> Validate Form </button>
                                    <a href="/players" type="reset" class="button"> Cancel </a>
                                </div>
                              </form>
                            </div>
                        </div>
                    </div>
                    <!-- end: .admin-form -->
                </div>
                <!-- Begin: Admin Form -->
            </div>
        </div>
        <!-- end: .tray-center -->

</section>


@endsection

resources/views/players/edit-email.blade.php
@extends('layouts.admin')

@section('content')
<!-- Start: Topbar -->

@include('layouts.includes.admin.header-breadcrumb')

<!-- End: Topbar -->
<section id="content" class="table-layout animated fadeIn">
  <!-- Request Google Analytics -->
  <div class="panel panel-system panel-border top mb35">
    <div class="panel-heading">
      <span class="panel-title">Edit Email</span>
    </div>
    <div class="panel-body bg-light dark">
      <div class="admin-form">

        {{-- <h5 class="text-muted fw400 mb10"> Edit email</h5> --}}
        <form  method="POST" action="{{ route('players.email.edit') }}">
          @csrf
          <div class="section mbn">
            <label class="field prepend-icon">
              <textarea class="gui-textarea" id="email-text" name="email_text" placeholder="Email text here">{{ $player->email_text }}</textarea>
              <label for="email-text" class="field-icon"></label>
            </label>

            <div class="text-right mt15">
              <button class="btn btn-sm btn-primary">submit</button>
            </div>
          </div>
          <input type="hidden" name="player_espn_id" value="{{ $player->espn_id }}">
        </form>
        <!-- end section -->

      </div>
    </div>
  </div>
</section>


@endsection

resources/views/players/index.blade.php
@extends('layouts.admin')

@push('header-links')
  <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-select.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('css/custom-bootstrap-select.css') }}">
@endpush

@section('content')
<header id="topbar">
  <div class="topbar-left">
    <ol class="breadcrumb">
      <li class="crumb-active">
        <a href="header-links">Dashboard</a>
      </li>
      <li class="crumb-icon">
        <a href="/">
          <span class="glyphicon glyphicon-home"></span>
        </a>
      </li>
      <li class="crumb-link">
        <a>Players</a>
      </li>
      <!--<li class="crumb-trail">Dashboard</li>-->
    </ol>
  </div>

</header>

<section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
    <div class="tray tray-center">

        <div class="panel mb25 mt5">
            <div class="panel-body p25 pb5">
              <div class="tab-content pn br-n admin-form">
                  <div class="section row mbn">
                    <div class="col-sm-8">
                      <label class="field option mt10">
                        <!--<input type="checkbox" name="info" checked>-->
                        <span class=""></span>Add Player
                      </label>
                    </div>
                    <div class="col-sm-4">
                      <p class="text-right">
                          <a href="{{url('/admin/players/create')}}" class="btn btn-primary" type="button">Add Player</a>
                      </p>
                    </div>
                  </div>
                  <!-- end section -->
              </div>
            </div>
          </div>

          <div class="mb15" style="width: 20%; margin-left: auto">
            <form id="select-player-form-id" method="GET" action="{{ route('search-player') }}">
              <select type="text" name="espn_id" id="search-player-input" data-live-search="true" title="search">
              </select>
            </form>
          </div>

          <div class="panel">
              <div class="panel-body pn">
                <div class="table-responsive">
                  <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                    <thead>
                      <tr class="bg-light">
                        <th class="text-center">#</th>
                        <th class="">First Name</th>
                        <th class="">Last Name</th>
                        <th class="">Text to mail</th>
                      </tr>
                    </thead>

                    <tbody>
                      @foreach($players as $player)
                          <tr>
                              <td>{{ $loop->iteration + $paginationCount * $page}}</td>
                              <td>{{ $player->first_name }}</td>
                              <td>{{ $player->last_name }}</td>
                              <td>
                                <a href="{{ route('players.email.edit', ['player_espn_id' => $player->espn_id]) }}" class="btn-primary btn btn-sm">Edit</a>
                              </td>
                          </tr>
                      @endforeach
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="panel-footer clearfix">
                      {{ $players->links() }}
              </div>
          </div>
    </div>
</section>

@endsection

@section('page-js-script')
  <script src="{{ asset('js/ajax-bootstrap-select.min.js') }}"></script>
  <script src="{{ asset('js/bootstrap-select.min.js') }}"></script>


  <script type="text/javascript">
    $("#search-player-input").selectpicker({
      style : '',
      styleBase : 'form-control'
    }).ajaxSelectPicker({
      locale: {
        emptyTitle: " "
      },
      ajax: {
        url: $('meta[name="base-url"]').attr('content') + '/admin/players/all/search', 
        type: 'GET',
        dataType: 'json',

        data: {
          search_text: '@{{{q}}}'
        }
      },
      // function to preprocess JSON data
      preprocessData: function (data) {
        var i, l = data.length, array = [];
        if (l) {
            for (i = 0; i < l; i++) {
                array.push($.extend(true, data[i], {
                    text : data[i].full_name,
                    value: data[i].espn_id,
                    // data : {
                    //     subtext: 'test'
                    // }
                }));
            }
        }
        // You must always return a valid array when processing data. The
        // data argument passed is a clone and cannot be modified directly.
        return array;
      }
    });


    $("#search-player-input").on('changed.bs.select', function() {
      $('#select-player-form-id').submit();
    });
  </script>
@stop